### ISSUE TITLE
Linux Update && Upgrade error

### ISSUE THREAD

**Issue by ingahaindongo** [M157q/py-feedr#13]
root@w3w:~# apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up python3.4 (3.4.2-1+deb8u3) ...
  File "/usr/lib/python3.4/http/client.py", line 1014
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
                                                                     ^
SyntaxError: invalid syntax
dpkg: error processing package python3.4 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 python3.4
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ingahaindongo** [comment]
Please help me understand this error and if possible provide useful advice

**Comment by M157q** [comment]
@ingahaindongo 
Just follow this thread on Reddit: https://www.reddit.com/r/debian/comments/c53ef1/problem_update_python_34_debian_8/

The problem is related to the Python 3.4 patch, not the code in this repo.
BTW, Python 3.4 had reached EOL in 2019-03-16
FYI, https://devguide.python.org/devcycle/#end-of-life-branches
